using Entities.Models.Enums;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Entities.Models
{
    [Table("transport_request")]
    public class TransportRequest
    {
        [Key]
        [Column("IDTransportRequest")]
        public Guid Id { get; set; }

        [ForeignKey(nameof(Department))]
        [Required(ErrorMessage = "IDDepartment is required")]
        public Guid IDDepartment { get; set; }

        [ForeignKey(nameof(Volunteer))]
        [Required(ErrorMessage = "IDCoordinator is required")]
        public int IDCoordinator { get; set; }

        [Required(ErrorMessage = "TransportType is required")]
        public TransportType TransportType { get; set; }

        [Required(ErrorMessage = "PlaceType is required")]
        public PlaceType PlaceType { get; set; }

        [Required(ErrorMessage = "IDPlace is required")]
        public Guid IDPlace { get; set; }

        [Required(ErrorMessage = "Place is required")]
        public string Place { get; set; }

        [Required(ErrorMessage = "Date is required")]
        public DateTime Date { get; set; }

        [Required(ErrorMessage = "TimeRange is required")]
        public string TimeRange { get; set; }

        [Required(ErrorMessage = "Detail is required")]
        public string Detail { get; set; }

        public string Observations { get; set; }

        [Required(ErrorMessage = "Priority is required")]
        public PriorityType Priority { get; set; }

        [Required(ErrorMessage = "Status is required")]
        public StatusType Status { get; set; }

        public string CommentByDirector { get; set; }

        //Autogenerated Timestamp
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
    }
}
